"""add deactivation_date to fleet and tools

Revision ID: 7cb46e3fbac9
Revises: 7f9c5e48f5c2
Create Date: 2026-03-01 23:37:31.711515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb46e3fbac9'
down_revision: Union[str, Sequence[str], None] = '7f9c5e48f5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_labor_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_labor_costs_id'))

    op.drop_table('project_labor_costs')
    with op.batch_alter_table('monthly_labor_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_labor_costs_id'))

    op.drop_table('monthly_labor_costs')
    with op.batch_alter_table('fleet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivation_date', sa.Date(), nullable=True))

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivation_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('deactivation_date')

    with op.batch_alter_table('fleet', schema=None) as batch_op:
        batch_op.drop_column('deactivation_date')

    op.create_table('monthly_labor_costs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collaborator_id', sa.INTEGER(), nullable=False),
    sa.Column('competence_date', sa.DATE(), nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_days_found', sa.INTEGER(), nullable=True),
    sa.Column('calculated_daily_rate', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('unallocated_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_labor_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_labor_costs_id'), ['id'], unique=False)

    op.create_table('project_labor_costs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monthly_cost_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('days_worked', sa.INTEGER(), nullable=False),
    sa.Column('cost_value', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['monthly_cost_id'], ['monthly_labor_costs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_labor_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_labor_costs_id'), ['id'], unique=False)

    # ### end Alembic commands ###
