"""Add fiscal fields to ProjectBilling

Revision ID: 9b1f967a3e86
Revises: 9fe9840204b7
Create Date: 2025-12-22 22:28:29.441644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1f967a3e86'
down_revision: Union[str, Sequence[str], None] = '9fe9840204b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_labor_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_labor_costs_id'))

    op.drop_table('project_labor_costs')
    with op.batch_alter_table('monthly_labor_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_labor_costs_id'))

    op.drop_table('monthly_labor_costs')
    with op.batch_alter_table('project_billings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('SERVICE', 'MATERIAL', 'HYBRID', name='billingcategory'), nullable=True))
        batch_op.add_column(sa.Column('gross_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('net_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_iss', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_inss', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_irrf', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_pis', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_cofins', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_csll', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_icms', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_ipi', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('value_st', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_billings', schema=None) as batch_op:
        batch_op.drop_column('value_st')
        batch_op.drop_column('tax_ipi')
        batch_op.drop_column('tax_icms')
        batch_op.drop_column('retention_csll')
        batch_op.drop_column('retention_cofins')
        batch_op.drop_column('retention_pis')
        batch_op.drop_column('retention_irrf')
        batch_op.drop_column('retention_inss')
        batch_op.drop_column('retention_iss')
        batch_op.drop_column('net_value')
        batch_op.drop_column('gross_value')
        batch_op.drop_column('category')

    op.create_table('monthly_labor_costs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collaborator_id', sa.INTEGER(), nullable=False),
    sa.Column('competence_date', sa.DATE(), nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_days_found', sa.INTEGER(), nullable=True),
    sa.Column('calculated_daily_rate', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('unallocated_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_labor_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_labor_costs_id'), ['id'], unique=False)

    op.create_table('project_labor_costs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monthly_cost_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('days_worked', sa.INTEGER(), nullable=False),
    sa.Column('cost_value', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['monthly_cost_id'], ['monthly_labor_costs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_labor_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_labor_costs_id'), ['id'], unique=False)

    # ### end Alembic commands ###
